### PR TITLE
Fixed various typos and formatting issues in the Script Canvas Workflow Tests

### PR DESCRIPTION
**Pull request by LB-TomaszSerwanski**
* Sript Canvas Workflow Tests (https://github.com/o3de/sig-content/blob/main/testing-guidance/workflow-tests/scripting/script-canvas-tests.md):
  * Changed "asterix" to "asterisk" in the "Verify main Script Canvas window pane renders a script canvas graph" section.
  * Removed the duplicated "in" in the "Use and observe minimap behavior" section.
  * Capitalized the "Variable Manager" in the "Create a variable node with Variable Manager" section. 
  * Capitalized the "Asset Editor" in the "Create a 2nd script canvas graph file and use a script event to make the two files communicate during gameplay" section.
  * Listed the Example Functions  in the "Create a user function and verify its input/output when called from another graph" section.
  * Removed an obsolete asterisk in the "Create a user function and verify its input/output when called from another graph" section.
  * Added the missing period symbols after various sentences across the document.
  * Fixed broken "Script Canvas Editor Interface Guide" documentation link.

Signed-off-by: LB-TomaszSerwanski <tomasz.serwanski@lionbridge.com>

### CODE REVIEW

**Comment by michleza** [comment]
this is still relevant. let's resolve the merge conflict and then bring these changes into the md

**Comment by michleza** [comment]
@LB-TomaszSerwanski  I tried to use the web editor to resolve the conflicts but it undid my work.

**Comment by LB-TomaszSerwanski** [comment]
Hi @michleza, @FuzzyCarterAWS, it took more commits than it should as the formatting broke when resolving conflicts but the PR should be ready to merge now.

**Comment by michleza** [comment]
Formatting looks good to me. I'll merge this in

**Comment by LB-TomaszSerwanski** [comment]
Confirming that the pull request has been merged successfully.

**Pull request merged**
